const students = [
  {
    enrollmentId: '24CS10NE83',
    email: '24cs10ne83@mitsgwl.ac.in',
    name: 'Nemish Patel',
    branch: 'CSE',
    year: 2,
  },
  {
    enrollmentId: '24CS10NE84',
    email: '24cs10ne84@mitsgwl.ac.in',
    name: 'Priya Sharma',
    branch: 'CSE',
    year: 2,
  },
  {
    enrollmentId: '24CS10NE85',
    email: '24cs10ne85@mitsgwl.ac.in',
    name: 'Arjun Mehta',
    branch: 'IT',
    year: 2,
  },
  {
    enrollmentId: '24CS10AB12',
    email: '24cs10ab12@mitsgwl.ac.in',
    name: 'Sara Iyer',
    branch: 'ECE',
    year: 2,
  },
  {
    enrollmentId: '23CS10NE20',
    email: '23cs10ne20@mitsgwl.ac.in',
    name: 'Raj Kumar',
    branch: 'ME',
    year: 3,
  },
  {
    enrollmentId: '23IT10AB34',
    email: '23it10ab34@mitsgwl.ac.in',
    name: 'Ananya Joshi',
    branch: 'IT',
    year: 3,
  },
  {
    enrollmentId: '22EC10CD56',
    email: '22ec10cd56@mitsgwl.ac.in',
    name: 'Vikram Singh',
    branch: 'ECE',
    year: 4,
  },
  {
    enrollmentId: '22CS10NE61',
    email: '22cs10ne61@mitsgwl.ac.in',
    name: 'Meera Nair',
    branch: 'CSE',
    year: 4,
  },
  {
    enrollmentId: '24ME10AB07',
    email: '24me10ab07@mitsgwl.ac.in',
    name: 'Kiran Patil',
    branch: 'ME',
    year: 2,
  },
  {
    enrollmentId: '23CS10CD45',
    email: '23cs10cd45@mitsgwl.ac.in',
    name: 'Deepak Verma',
    branch: 'CSE',
    year: 3,
  },
  {
    enrollmentId: '24IT10NE19',
    email: '24it10ne19@mitsgwl.ac.in',
    name: 'Pooja Reddy',
    branch: 'IT',
    year: 2,
  },
  {
    enrollmentId: '22IT10AB88',
    email: '22it10ab88@mitsgwl.ac.in',
    name: 'Sanjay Gupta',
    branch: 'IT',
    year: 4,
  },
  {
    enrollmentId: '23EC10CD33',
    email: '23ec10cd33@mitsgwl.ac.in',
    name: 'Divya Menon',
    branch: 'ECE',
    year: 3,
  },
  {
    enrollmentId: '24CS10CD71',
    email: '24cs10cd71@mitsgwl.ac.in',
    name: 'Rohit Bansal',
    branch: 'CSE',
    year: 2,
  },
  {
    enrollmentId: '22ME10NE50',
    email: '22me10ne50@mitsgwl.ac.in',
    name: 'Lakshmi Pillai',
    branch: 'ME',
    year: 4,
  },
  {
    enrollmentId: '24CS10PA89',
    email: '24cs10pa89@mitsgwl.ac.in',
    name: 'Parth Student',
    branch: 'CSE',
    year: 2,
  },
];

export default students;
